// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

interface PrismaPostgresApiKey {
  databaseUrl?: unknown;
  shadowDatabaseUrl?: unknown;
}

function readPrismaPostgresApiKey(databaseUrl: string | undefined) {
  if (!databaseUrl?.startsWith("prisma+postgres://")) {
    return null;
  }

  try {
    const apiKey = new URL(databaseUrl).searchParams.get("api_key");

    if (!apiKey) {
      return null;
    }

    return JSON.parse(
      Buffer.from(apiKey, "base64url").toString("utf8"),
    ) as PrismaPostgresApiKey;
  } catch {
    return null;
  }
}

const databaseUrl = process.env["DATABASE_URL"];
const prismaPostgresApiKey = readPrismaPostgresApiKey(databaseUrl);
const directDatabaseUrl =
  process.env["DIRECT_DATABASE_URL"] ??
  (typeof prismaPostgresApiKey?.databaseUrl === "string"
    ? prismaPostgresApiKey.databaseUrl
    : undefined) ??
  databaseUrl;
const shadowDatabaseUrl =
  process.env["SHADOW_DATABASE_URL"] ??
  (typeof prismaPostgresApiKey?.shadowDatabaseUrl === "string"
    ? prismaPostgresApiKey.shadowDatabaseUrl
    : undefined);

export default defineConfig({
  schema: "prisma/",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: directDatabaseUrl,
    shadowDatabaseUrl,
  },
});
